import { cleanupOutdatedCaches, precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

cleanupOutdatedCaches();
clientsClaim();
self.skipWaiting();

// 1. Precache Build Artifacts (JS, CSS, HTML generated by Vite)
precacheAndRoute(self.__WB_MANIFEST);

// 2. Navigation Fallback (CRITICAL for Offline SPA)
// This serves index.html if the user navigates to a URL while offline.
// Assumes index.html is included in the __WB_MANIFEST (it is by default in VitePWA).
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler);
registerRoute(navigationRoute);

// 3. Explicitly Precache Critical External Assets on Install
self.addEventListener('install', (event) => {
  event.waitUntil(
    Promise.all([
      // Cache Tailwind
      caches.open('tailwind-cdn').then((cache) => {
        return cache.add('https://cdn.tailwindcss.com').catch(err => console.warn('Failed to cache Tailwind', err));
      }),
      // Cache Google Font Stylesheet
      caches.open('google-fonts-stylesheets').then((cache) => {
        return cache.add('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Share+Tech+Mono&display=swap').catch(err => console.warn('Failed to cache Fonts', err));
      })
    ])
  );
});

// 4. Runtime Caching Routes

// Tailwind CSS
registerRoute(
  ({ url }) => url.origin === 'https://cdn.tailwindcss.com',
  new CacheFirst({
    cacheName: 'tailwind-cdn',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 1, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  })
);

// Google Fonts Stylesheets
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// Google Fonts Webfonts (WOFF2 files referenced by the stylesheet)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  })
);

// Images (Unsplash, Flaticon)
registerRoute(
  ({ url }) => 
    url.origin === 'https://images.unsplash.com' || 
    url.origin === 'https://cdn-icons-png.flaticon.com',
  new CacheFirst({
    cacheName: 'image-assets',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 * 30 }),
    ],
  })
);